site_name: FreeTensor

theme:
    name: "readthedocs"

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                selection:
                    docstring_style: numpy
                    inherited_members: True
        watch:
            - python/
            - include/
            - src/

extra_css: [extra.css]
