site_name: FreeTensor

theme:
    name: "readthedocs"
    logo: "resource/logo-light.png"

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                selection:
                    docstring_style: numpy
                    inherited_members: True
        watch:
            - python/
            # We cannot watch build/. Reload mkdocs manually after rebuilding

extra_javascript:
    # The followings are required by MathJax
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true  # Required by MathJax

nav:
    - 'FreeTensor':
        - 'Home': 'index.md'
        - 'GitHub': 'https://github.com/roastduck/FreeTensor'
    - 'User Guide':
        - 'Get Started': 'guide/index.md'
        - 'Build and Run': 'guide/build-and-run.md'
        - 'Your First Program with FreeTenor': 'guide/first-program.md'
        - 'Optimize a Program with Schedules': 'guide/schedules.md'
        - 'Running on a GPU': 'guide/gpu.md'
        - 'Automatic Differentiation': 'guide/ad.md'
    - 'API Reference':
        - 'Python API': 'api.md'
        - 'Internal C++ Interface': 'doxygen/html/index.html'
    - 'About':
        - 'Contributing': 'about/contrib.md'
        - 'Publication': 'about/pub.md'
        - 'License': 'https://github.com/roastduck/FreeTensor/blob/master/LICENSE'

extra_css: [extra.css]
