import ffi
import functools

from typing import Optional
from ffi import CPU, GPU, Array

from . import config
from .codegen import NativeCode


class Target(ffi.Target):
    '''
    A target architecture

    A Target can be used as a "with" scope, then all the `lower`s and `codegen`s
    will use it by default. In this style, it also sets the default Device as the
    0-th device of the given Target. E.g:

    ```
    with Target(...):
        ast = lower(ast)  # Use the Target above by default
        a = Array(...)  # Use the 0-th device of the Target above by default
    ```
    '''

    def __init__(self, use_native_arch: bool = True):
        super(Target, self).__init__(use_native_arch)

    def __enter__(self):
        self.old_target = config.default_target()
        self.old_device = config.default_device()
        config.set_default_target(self)
        config.set_default_device(Device(self, 0))
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        config.set_default_target(self.old_target)
        config.set_default_device(self.old_device)


class Device(ffi.Device):
    '''
    A computing device of a Target

    E.g. suppose GPU() is a Target (architecture), then Device(GPU(), 0) means
    the 0-th GPU (device)

    A Device can be used as a "with" scope, then all the `Array`s and `Driver`s
    will use it by default. In this style, it also sets the default Target. E.g:

    ```
    with Device(...):
        ast = lower(ast)  # Use the Target of the Device above by default
        a = Array(...)  # Use the Device above by default
    ```
    '''

    def __init__(self, target: Target, num: int = 0):
        super(Device, self).__init__(target, num)

    def __enter__(self):
        self.old_target = config.default_target()
        self.old_device = config.default_device()
        config.set_default_target(self.target())
        config.set_default_device(self)
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        config.set_default_target(self.old_target)
        config.set_default_device(self.old_device)


class Driver(ffi.Driver):

    def __init__(self,
                 func: ffi.Func,
                 src: str,
                 device: Optional[Device] = None):
        '''
        Compile a program using a backend compiler and load it into memory

        This class is for internal use. Please consider using `build_binary`

        Parameters
        ----------
        func : ffi.Func
            AST of the function, where the function signature is needed to
            determine the parameters and return values
        src : str
            Native code generated from codegen
        device : Device (Optional)
            The device to run the program. If omitted, use the default device
            in config
        '''
        src = str(src)
        if device is not None:
            super(Driver, self).__init__(func, src, device)
        else:
            super(Driver, self).__init__(func, src)

    def set_params(self, *args, **kws):
        super(Driver, self).set_params(args, kws)

    def __call__(self, *args, **kws):
        self.set_params(*args, **kws)
        self.run()
        lst = self.collect_returns()
        if len(lst) == 1:
            return lst[0]
        else:
            return lst


def build_binary(code: Optional[NativeCode] = None,
                 device: Optional[Device] = None):
    '''
    Compile a program using a backend compiler and load it into memory

    Parameters
    ----------
    code : NativeCode
        Native code generated by `codegen`. If not specified, a partial
        function is returned, which can be used as a decorator
    device : Device (Optional)
        The device to run the program. If omitted, use the default device
        in config
    '''

    if code is not None:
        return Driver(code.func, code.code, device)
    else:
        f = build_binary
        if device is not None:
            f = functools.partial(f, device=device)
        return f
