name: Format C++ and Python

on: [push]

jobs:
  python-format-check:
    name: Python Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AlexanderMelde/yapf-action@master
  cxx-format-check:
    name: C++ Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'runtime'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
