name: Format C++ and Python

on: [pull_request]

jobs:
  python-format-check:
    name: Python Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run YAPF style check for Python scripts.
      uses: AlexanderMelde/yapf-action@master
  cxx-format-check:
    name: C++ Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '13'
        check-path: .
