name: Format C++ and Python

on: [pull_request]

jobs:
  cxx-format-check:
    name: C++ Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clang Format
      uses: RafikFarhad/clang-format-github-action@v3
      with:
        sources: include/**/*.h,runtime/**/*.h,runtime/**/*.cc,src/**/*.h,src/**/*.cc,ffi/**/*.h,ffi/**/*.cc
        style: file
  python-formatting-check:
    name: Python Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: YAPF
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --verbose
